import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  documentSidebar: [{type: 'autogenerated', dirName: '.'}],

  portfolioSidebar: [
    {
      type: 'category',
      label: 'Portfolio',
      items: [
        {
          type: 'category',
          label: 'Chatting Application',
          items: [
            'Portfolio/ChattingApplication/index',
            'Portfolio/ChattingApplication/architecture',
            'Portfolio/ChattingApplication/cicdPipeline',
            {
              type: 'category',
              label: 'Technical Decisions',
              link: {
                type: 'doc',
                id: 'Portfolio/ChattingApplication/technicalDecisions/technicalDecisions'
              },
              items: [{
                type: 'autogenerated',
                dirName: 'Portfolio/ChattingApplication/technicalDecisions'
              }],
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
