import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  financeSidebar: [
    {
      type: 'category',
      label: 'Finance',
      link: {
        type: 'generated-index',
        title: 'Finance',
        description: '재테크 문서 모음',
        slug: '/',
      },
      collapsed: false,
      collapsible: false,
      items: [
        { type: 'autogenerated', dirName: '.' }
      ]
    }
  ]
};

export default sidebars;

