import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  portfolioSidebar: [
    {
      type: 'category',
      label: 'Portfolio',
      link: {
        type: 'generated-index',
        title: 'Portfolio',
        description: '프로젝트/작품집 모음',
        slug: '/',
      },
      collapsed: false,
      collapsible: false,
      items: [
        { type: 'autogenerated', dirName: '.' }
      ]
    }
  ]
};

export default sidebars;

